## Deprecated because gpdb6 and gpdb7 should use different pr pipelines
## ======================================================================
## resources
## ======================================================================
resource_types:
  - name: pull_request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.21.0
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: pgbouncer_pr
    type: pull_request
    source:
      access_token: ((gpdb-git-access-token))
      base_branch: "6X"
      repository: greenplum-db/pgbouncer
      disable_forks: true
      #required_review_approvals: 1
      ignore_paths:
        - doc/*
        - README*

  - name: gpdb6-centos7-test
    type: registry-image
    source:
      repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test
      tag: latest

  - name: gpdb6_src
    type: git
    source:
      branch: 6X_STABLE
      uri: https://github.com/greenplum-db/gpdb.git
      ignore_paths:
        - gpdb-doc/*
        - README*

  - name: bin_gpdb6_centos7
    type: gcs
    source:
      bucket: ((dataflow/gpdb6-bin-bucket-name))
      json_key: ((dataflow/concourse-gcs-resources-service-account-key))
      regexp: server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz

  - name: gpdb6-rocky8-build
    source:
      repository: gcr.io/data-gpdb-public-images/gpdb6-rocky8-build
      tag: latest
    type: registry-image

  - name: gpdb6-rocky8-test
    source:
      repository: gcr.io/data-gpdb-public-images/gpdb6-rocky8-test
      tag: latest
    type: registry-image

  - name: bin_gpdb6_rocky8_rc
    source:
      bucket: pivotal-gpdb-concourse-resources-prod
      json_key: ((concourse-gcs-resources-service-account-key))
      regexp: server/published/gpdb6/server-rc-(.*)-rocky8_x86_64.debug.tar.gz
    type: gcs

  - name: gpdb6-sles12-build
    source:
      password: ((data-gpdb-private-images-container-registry-readonly-service-account-key))
      repository: gcr.io/data-gpdb-private-images/gpdb6-sles12-build
      tag: latest
      username: _json_key
    type: registry-image

  - name: gpdb6-photon3-build
    source:
      repository: gcr.io/data-gpdb-public-images/gpdb6-photon3-build
      tag: latest
    type: registry-image

  - name: gpdb6-rocky9-build
    source:
      repository: gcr.io/data-gpdb-public-images/gpdb6-rocky9-build
      tag: latest
    type: registry-image
  - name: gpdb6-rocky9-test
    source:
      repository: gcr.io/data-gpdb-public-images/gpdb6-rocky9-test
      tag: latest
    type: registry-image
  - name: bin_gpdb6_rocky9_rc
    source:
      bucket: ((dataflow/gpdb6-bin-bucket-name))
      json_key: ((dataflow/concourse-gcs-resources-service-account-key))
      regexp: server/published/gpdb6/server-rc-(.*)-rhel9_x86_64.tar.gz
    type: gcs
jobs:
  - name: test_pgbouncer_gpdb6_centos7
    plan:
      - in_parallel:
          - get: pgbouncer_pr
            trigger: true
            version: every
          - get: gpdb6-centos7-test
          - get: gpdb6_src
          - get: bin_gpdb
            resource: bin_gpdb6_centos7
      - put: pgbouncer_pr
        params:
          path: pgbouncer_pr
          status: pending
      - task: build_pgbouncer
        input_mapping:
          pgbouncer_src: pgbouncer_pr
          gpdb_src: gpdb6_src
        config:
          platform: linux
          inputs:
          - name: pgbouncer_src
          - name: gpdb_src
          outputs:
          - name: pgbouncer_compiled
          run:
            path: pgbouncer_src/concourse/scripts/build.bash
        image: gpdb6-centos7-test
        on_failure: &pr_failure
          put: pgbouncer_pr
          params:
            path: pgbouncer_pr
            status: failure
        timeout: 30m
      - task: psql_test
        input_mapping:
          pgbouncer_src: pgbouncer_compiled
          gpdb_src: gpdb6_src
        config:
          platform: linux
          inputs:
            - name: pgbouncer_src
            - name: gpdb_src
            - name: bin_gpdb
          run:
            path: pgbouncer_src/concourse/scripts/psql_test.bash
        image: gpdb6-centos7-test
        params:
          TARGET_OS: centos7
        on_failure: *pr_failure
        timeout: 30m

  - name: test_pgbouncer_gpdb6_rocky8
    plan:
      - in_parallel:
          - get: pgbouncer_pr
            trigger: true
            version: every
          - get: gpdb6-rocky8-build
          - get: gpdb6-rocky8-test
          - get: gpdb6_src
          - get: bin_gpdb
            resource: bin_gpdb6_rocky8_rc
      - put: pgbouncer_pr
        params:
          path: pgbouncer_pr
          status: pending
      - task: build_pgbouncer
        input_mapping:
          pgbouncer_src: pgbouncer_pr
          gpdb_src: gpdb6_src
        config:
          platform: linux
          inputs:
          - name: pgbouncer_src
          - name: gpdb_src
          outputs:
          - name: pgbouncer_compiled
          run:
            path: pgbouncer_src/concourse/scripts/build.bash
        image: gpdb6-rocky8-build
        on_failure: &pr_failure
          put: pgbouncer_pr
          params:
            path: pgbouncer_pr
            status: failure
        timeout: 30m
      - task: psql_test
        input_mapping:
          pgbouncer_src: pgbouncer_compiled
          gpdb_src: gpdb6_src
        config:
          platform: linux
          inputs:
            - name: pgbouncer_src
            - name: gpdb_src
            - name: bin_gpdb
          run:
            path: pgbouncer_src/concourse/scripts/psql_test.bash
        image: gpdb6-rocky8-test
        params:
          TARGET_OS: rocky8
        on_failure: *pr_failure
        timeout: 30m
  - name: test_pgbouncer_gpdb6_rocky9
    plan:
      - in_parallel:
          - get: pgbouncer_pr
            trigger: true
            version: every
          - get: gpdb6-rocky9-build
          - get: gpdb6-rocky9-test
          - get: gpdb6_src
          - get: bin_gpdb
            resource: bin_gpdb6_rocky9_rc
      - put: pgbouncer_pr
        params:
          path: pgbouncer_pr
          status: pending
      - task: build_pgbouncer
        input_mapping:
          pgbouncer_src: pgbouncer_pr
          gpdb_src: gpdb6_src
        config:
          platform: linux
          inputs:
          - name: pgbouncer_src
          - name: gpdb_src
          outputs:
          - name: pgbouncer_compiled
          run:
            path: pgbouncer_src/concourse/scripts/build.bash
        image: gpdb6-rocky9-build
        on_failure: &pr_failure
          put: pgbouncer_pr
          params:
            path: pgbouncer_pr
            status: failure
        timeout: 30m
      - task: psql_test
        input_mapping:
          pgbouncer_src: pgbouncer_compiled
          gpdb_src: gpdb6_src
        config:
          platform: linux
          inputs:
            - name: pgbouncer_src
            - name: gpdb_src
            - name: bin_gpdb
          run:
            path: pgbouncer_src/concourse/scripts/psql_test.bash
        image: gpdb6-rocky9-test
        params:
          TARGET_OS: rocky9
        on_failure: *pr_failure
        timeout: 30m

  - name: build_pgbouncer_gpdb6_photon3
    plan:
      - in_parallel:
          - get: pgbouncer_pr
            trigger: true
            version: every
          - get: gpdb6-photon3-build
      - put: pgbouncer_pr
        params:
          path: pgbouncer_pr
          status: pending
      - task: build_pgbouncer
        input_mapping:
          pgbouncer_src: pgbouncer_pr
        config:
          platform: linux
          inputs:
          - name: pgbouncer_src
          outputs:
          - name: pgbouncer_compiled
          run:
            path: pgbouncer_src/concourse/scripts/build.bash
        image: gpdb6-photon3-build
        on_failure: &pr_failure
          put: pgbouncer_pr
          params:
            path: pgbouncer_pr
            status: failure
        timeout: 30m

  - name: build_pgbouncer_gpdb6_sles12
    plan:
      - in_parallel:
          - get: pgbouncer_pr
            trigger: true
            version: every
          - get: gpdb6-sles12-build
      - put: pgbouncer_pr
        params:
          path: pgbouncer_pr
          status: pending
      - task: build_pgbouncer
        input_mapping:
          pgbouncer_src: pgbouncer_pr
        config:
          platform: linux
          inputs:
          - name: pgbouncer_src
          outputs:
          - name: pgbouncer_compiled
          run:
            path: pgbouncer_src/concourse/scripts/build.bash
        image: gpdb6-sles12-build
        on_failure: &pr_failure
          put: pgbouncer_pr
          params:
            path: pgbouncer_pr
            status: failure
        timeout: 30m

  - name: set-pr-status
    plan:
      - in_parallel:
          - get: pgbouncer_pr
            trigger: true
            passed:
              - test_pgbouncer_gpdb6_centos7
              - test_pgbouncer_gpdb6_rocky8
              - build_pgbouncer_gpdb6_photon3
              - build_pgbouncer_gpdb6_sles12
      - put: report_pr_success
        resource: pgbouncer_pr
        params:
          path: pgbouncer_pr
          status: success
